// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://watojqhsegqbpcilpxic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhdG9qcWhzZWdxYnBjaWxweGljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4MDMxMDUsImV4cCI6MjA1MzM3OTEwNX0.E6SgpXE2-hrQhz30CwizczfS3OQEKkLbEWA5bptHX8s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);